### ISSUE TITLE
Sticky sidebar overflows on mobile

### ISSUE THREAD

**Issue by isdampe** [splashkit/splashkit.io#11]
When viewing the API section on a mobile device, the sticky sidebar renders beneath the guide text.

Note: I'll have a crack at submitting a patch for this if I get time in the week

On Chrome Android:

![screenshot_2017-10-22-20-58-21](https://user-images.githubusercontent.com/7271686/31860805-5bbc6106-b76c-11e7-8763-56f38c603ae4.png)

**Comment by alexcu** [comment]
Hi Richard

Good pick up. This has been fixed in an upcoming PR.

Cheers,
Alex

**Comment by alexcu** [comment]
Fixed with 22b3adc5

**Comment by isdampe** [comment]
Worlds fastest fix!
