### ISSUE TITLE
Getting "Unable to connect" when accessing https://splashkit.io

### ISSUE THREAD

**Issue by gcarreno** [splashkit/splashkit.io#35]
Hi there,

When you access `http://splashkit.io` it correctly redirects to `https://www.splashkit.io`.

When you add the `s`, making it `https://splashkit.io`, my Firefox 93.0 on Ubuntu 21.04 64b complains it cannot connect.

Funny thing is that if I use curl I get this:
```console
$ curl splashkit.io
<a href='https://www.splashkit.io/'>Found</a>.
```
I'm suspecting that it could be caching related if you are using CloudFlare.
I've had similar issues with another page and I'm still trying to debug it with the web master there.

Cheers,
Gus

**Comment by jakerenzella** [comment]
Hey @gcarreno I've noticed this too recently, I'm not sure what the issue is as it popped up without making any changes. I'll have a quick look at the DNS settings. I believe we're using Github Pages to host this so I'll have a look there too.

**Comment by jakerenzella** [comment]
As a short update, I think the issue is that the DNS is only set to redirect www.splashkit.io via https, not as an apex domain. So www.splashkit.io should redirect over https. I will find who has the domain details to change this 👍

**Comment by jakerenzella** [comment]
This is now resolved

**Comment by gcarreno** [comment]
Hey Jake(@jakerenzella),

Thanks for sorting this out :)

Cheers,
Gus
