### ISSUE TITLE
Site needs an awesome favicon

### ISSUE THREAD

**Issue by jakerenzella** [splashkit/splashkit.io#5]
<img width="219" alt="screen shot 2017-09-12 at 10 19 17 pm" src="https://user-images.githubusercontent.com/5138218/30325525-727d19d6-9808-11e7-848f-57327e704eb3.png">

:(

**Comment by alexcu** [comment]
Agreed. Can we make a nice 16x16 one (not just shrunk down, but actually pixel-by-pixel)?

**Comment by jakerenzella** [comment]
d4ecacec50e6d2d4e58760b85d9c0ac5339a4a87
